version: '3.9'

services:
  postgres:
    image: postgres:16
    container_name: postgres_parts
    restart: unless-stopped
    environment:
      POSTGRES_USER: parts_user
      POSTGRES_PASSWORD: parts_pass
      POSTGRES_DB: parts_db
    ports:
      - "5432:5432"
    volumes:
      - ./bd:/var/lib/postgresql/data

